name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.11.0
        uses: actions/setup-node@v4
        with:
          node-version: 22.11.0
          cache: "npm"
      - run: npm ci
      - run: npm run pretty
      - run: npm run lint
